# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FiveInARow' do

pod 'AFNetworking', '~> 3.0.0’
pod 'SDWebImage', '~> 3.8.1'
pod 'Masonry', '~> 1.0.1'
pod 'YYKit', '~> 1.0.7'

end

